# Generated by Django 5.0.6 on 2024-06-04 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0003_certificate_chaireview_store'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='store',
            table=None,
        ),
    ]
