# Generated by Django 5.0.6 on 2024-06-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0004_alter_store_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='expiration_date',
            field=models.DateTimeField(),
        ),
    ]
