name: Deploy Django to VPS
on:
  push:
    branches:
      - main  # Replace with your desired branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        check-latest: false
        token: ${{ secrets.GITHUB_TOKEN }}
        update-environment: true
        allow-prereleases: false
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Prepare SSH keys and known_hosts
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 68.183.62.210 >> ~/.ssh/known_hosts
    - name: Test SSH connection
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no root@68.183.62.210 "echo 'SSH connection successful'"
    - name: Deploy to VPS
      run: |
        scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r . root@68.183.62.210:/root/Django
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no root@68.183.62.210 "/root/Django/deploy-script.sh"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST_USERNAME: root
