name: Deploy Django to VPS

on:
  push:
    branches:
      - main  # Replace with your desired branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        check-latest: false
        token: ${{ secrets.GITHUB_TOKEN }}
        update-environment: true
        allow-prereleases: false

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to VPS
      env:
        HOST_USERNAME: root
        HOST_PASSWORD: puNxMV2WqmJpZB9D
        pythonLocation: /opt/hostedtoolcache/Python/3.10.14/x64
        PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.10.14/x64/lib/pkgconfig
        Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.14/x64
        Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.14/x64
        Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.14/x64
        LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.14/x64/lib
      run: |
        scp -r . $HOST_USERNAME@68.183.62.210:/root/Django
        ssh $HOST_USERNAME@68.183.62.210 "/root/Django/deploy-script.sh"
