name: Deploy Django to VPS

on:
  push:
    branches:
      - main  # Replace with your desired branch

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


    - name: Deploy to VPS
      env:
        HOST_USERNAME: root
        HOST_PASSWORD: puNxMV2WqmJpZB9D
      run: |
        scp -r . $HOST_USERNAME@${{ secrets.HOST_IP }}: /root/Django
        ssh $HOST_USERNAME@${{ secrets.HOST_IP }} "/root/Django/deploy-script.sh"
